{% set name = "aiida-optimize" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-optimize-{{ version }}.tar.gz
  sha256: 5309fa588e9e71ef04e76ba1e4ea84bd85bf3c27e6760779f82623fcd01abff9
  patches:
  - install_requires.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >=3.8
    - aiida-core >=2.0.0,<3.0.0
    - numpy
    - scipy
    - decorator
    - pyyaml

test:
  imports:
    - aiida_optimize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aiida-optimize.readthedocs.io/
  summary: AiiDA Plugin for running optimization algorithms.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
